// Package render turns an assembled resume Document into Typst source and,
// when the typst binary is available, a PDF.
package render

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/beetlebugorg/resumed/internal/store"
)

// The ATS-hardened template ships inside the binary and is written next to the
// generated .typ so the file compiles standalone.
//
//go:embed ats-resume.typ
var templateTypst string

//go:embed ats-cover-letter.typ
var coverTemplateTypst string

// TemplateName is the filename the generated resume imports.
const TemplateName = "ats-resume.typ"

// CoverTemplateName is the filename the generated cover letter imports. It must
// differ from the generated letter's own filename ("cover-letter.typ") or the
// file imports itself and typst reports a cyclic import.
const CoverTemplateName = "ats-cover-letter.typ"

// Template exposes the embedded template so callers can write it to disk.
func Template() string { return templateTypst }

// CoverTemplate exposes the embedded cover letter template.
func CoverTemplate() string { return coverTemplateTypst }

// quote renders s as a Typst string literal.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// contentEscapes are the markup characters that must be backslash-escaped when
// text is emitted into Typst content mode (bullets, summaries). Typst only
// accepts escapes for characters that are actually special, so this set is
// deliberately exact rather than generous.
var contentEscapes = strings.NewReplacer(
	`\`, `\\`,
	`#`, `\#`,
	`$`, `\$`,
	`*`, `\*`,
	`_`, `\_`,
	"`", "\\`",
	`<`, `\<`,
	`>`, `\>`,
	`@`, `\@`,
	`[`, `\[`,
	`]`, `\]`,
	`~`, `\~`,
	`"`, `\"`,
	`'`, `\'`,
)

// esc escapes text for Typst content mode.
func esc(s string) string {
	s = contentEscapes.Replace(strings.TrimSpace(s))
	// A leading -, +, /, or = starts a list or heading; neutralise it.
	if s != "" {
		switch s[0] {
		case '-', '+', '/', '=':
			s = `\` + s
		}
	}
	return s
}

// labelForComment flattens a job label for the generated header comment. The
// em-dash in Job.Label reads fine in the web UI but looks out of place in a
// file a candidate may hand to an employer, so it is normalised here.
var commentLabel = strings.NewReplacer("\n", " ", "\u2014", "-", "\u2013", "-")

func labelForComment(s string) string { return commentLabel.Replace(s) }

// Typst generates the Typst source for a document.
func Typst(doc *store.Document) string {
	var b strings.Builder

	fmt.Fprintf(&b, "// Generated by resumed. Do not edit by hand.\n")
	if doc.Job != nil {
		fmt.Fprintf(&b, "// Tailored for: %s\n", labelForComment(doc.Job.Label()))
		if doc.Job.URL != "" {
			fmt.Fprintf(&b, "// %s\n", doc.Job.URL)
		}
	}
	fmt.Fprintf(&b, "\n#import %s: *\n\n", quote(TemplateName))

	// Header.
	b.WriteString("#show: resume.with(\n")
	fmt.Fprintf(&b, "  author: %s,\n", quote(doc.Profile.Name))
	fmt.Fprintf(&b, "  location: %s,\n", quote(doc.Profile.Location))
	b.WriteString("  contacts: (\n")
	for _, c := range doc.Contacts {
		if c.URL != "" {
			fmt.Fprintf(&b, "    [#link(%s)[%s]],\n", quote(c.URL), esc(c.Value))
		} else {
			fmt.Fprintf(&b, "    [%s],\n", esc(c.Value))
		}
	}
	b.WriteString("  ),\n)\n\n")

	if s := strings.TrimSpace(doc.Summary); s != "" {
		b.WriteString("= Summary\n\n")
		b.WriteString(esc(s))
		b.WriteString("\n\n")
	}

	if len(doc.Roles) > 0 {
		b.WriteString("= Experience\n\n")
		for _, r := range doc.Roles {
			b.WriteString("#exp(\n")
			fmt.Fprintf(&b, "  company: %s,\n", quote(r.Company))
			if r.Location != "" {
				fmt.Fprintf(&b, "  location: %s,\n", quote(r.Location))
			}
			fmt.Fprintf(&b, "  role: %s,\n", quote(r.Title))
			if d := r.Dates(); d != "" {
				fmt.Fprintf(&b, "  date: %s,\n", quote(d))
			}
			if r.Summary != "" {
				fmt.Fprintf(&b, "  summary: %s,\n", quote(r.Summary))
			}
			if len(r.Bullets) > 0 {
				b.WriteString("  details: [\n")
				for _, bl := range r.Bullets {
					fmt.Fprintf(&b, "    - %s\n", esc(bl.Text))
				}
				b.WriteString("  ],\n")
			}
			b.WriteString(")\n\n")
		}
	}

	if len(doc.SkillGroups) > 0 {
		b.WriteString("= Skills\n\n")
		b.WriteString("#skills((\n")
		for _, g := range doc.SkillGroups {
			fmt.Fprintf(&b, "  (%s, (\n", quote(g.Category))
			for _, n := range g.Names {
				fmt.Fprintf(&b, "    [%s],\n", esc(n))
			}
			b.WriteString("  )),\n")
		}
		b.WriteString("))\n\n")
	}

	if len(doc.Projects) > 0 {
		b.WriteString("= Projects\n\n")
		for _, p := range doc.Projects {
			b.WriteString("#proj(\n")
			fmt.Fprintf(&b, "  name: %s,\n", quote(p.Name))
			if p.URL != "" {
				fmt.Fprintf(&b, "  url: %s,\n", quote(p.URL))
			}
			if p.Date != "" {
				fmt.Fprintf(&b, "  date: %s,\n", quote(p.Date))
			}
			if p.Summary != "" {
				fmt.Fprintf(&b, "  summary: %s,\n", quote(p.Summary))
			}
			if len(p.Bullets) > 0 {
				b.WriteString("  details: [\n")
				for _, bl := range p.Bullets {
					fmt.Fprintf(&b, "    - %s\n", esc(bl.Text))
				}
				b.WriteString("  ],\n")
			}
			b.WriteString(")\n\n")
		}
	}

	if len(doc.Patents) > 0 {
		b.WriteString("= Patents\n\n")
		for _, p := range doc.Patents {
			b.WriteString("#patent(\n")
			fmt.Fprintf(&b, "  id: %s,\n", quote(p.PatentID))
			if p.URL != "" {
				fmt.Fprintf(&b, "  url: %s,\n", quote(p.URL))
			}
			if p.Date != "" {
				fmt.Fprintf(&b, "  date: %s,\n", quote(p.Date))
			}
			if p.Summary != "" {
				fmt.Fprintf(&b, "  summary: %s,\n", quote(p.Summary))
			}
			b.WriteString(")\n\n")
		}
	}

	return b.String()
}

// letterDate renders the stored timestamp as "2 January 2006" for the letter
// head. It uses the letter's own updated_at rather than the wall clock so a
// re-render does not silently re-date a letter that was already sent.
func letterDate(ts string) string {
	ts = strings.TrimSpace(ts)
	if ts == "" {
		return ""
	}
	for _, layout := range []string{"2006-01-02 15:04:05", "2006-01-02T15:04:05Z", "2006-01-02"} {
		if t, err := time.Parse(layout, ts); err == nil {
			return t.Format("January 2, 2006")
		}
	}
	return ""
}

// CoverLetterTypst generates the Typst source for a cover letter. The header
// is built from the same profile and contacts as the resume so the two
// documents read as one set.
func CoverLetterTypst(p store.Profile, contacts []store.Contact, job *store.Job, c *store.CoverLetter) string {
	var b strings.Builder

	fmt.Fprintf(&b, "// Generated by resumed. Do not edit by hand.\n")
	if job != nil {
		fmt.Fprintf(&b, "// Cover letter for: %s\n", labelForComment(job.Label()))
		if job.URL != "" {
			fmt.Fprintf(&b, "// %s\n", job.URL)
		}
	}
	fmt.Fprintf(&b, "\n#import %s: *\n\n", quote(CoverTemplateName))

	b.WriteString("#show: cover-letter.with(\n")
	fmt.Fprintf(&b, "  author: %s,\n", quote(p.Name))
	fmt.Fprintf(&b, "  location: %s,\n", quote(p.Location))
	b.WriteString("  contacts: (\n")
	for _, ct := range contacts {
		if ct.URL != "" {
			fmt.Fprintf(&b, "    [#link(%s)[%s]],\n", quote(ct.URL), esc(ct.Value))
		} else {
			fmt.Fprintf(&b, "    [%s],\n", esc(ct.Value))
		}
	}
	b.WriteString("  ),\n")

	if d := letterDate(c.UpdatedAt); d != "" {
		fmt.Fprintf(&b, "  date: %s,\n", quote(d))
	}

	// The recipient block carries only what the posting actually told us.
	// Inventing a hiring manager's name is exactly the kind of fabrication
	// this tool exists to prevent.
	var recipient []string
	if job != nil {
		if job.Company != "" {
			recipient = append(recipient, strings.TrimSpace(job.Company))
		}
		if job.Title != "" {
			recipient = append(recipient, "Re: "+strings.TrimSpace(job.Title))
		}
	}
	if len(recipient) > 0 {
		b.WriteString("  recipient: (\n")
		for _, line := range recipient {
			fmt.Fprintf(&b, "    [%s],\n", esc(line))
		}
		b.WriteString("  ),\n")
	}

	if c.Greeting != "" {
		fmt.Fprintf(&b, "  greeting: [%s],\n", esc(c.Greeting))
	}
	if c.Closing != "" {
		fmt.Fprintf(&b, "  closing: [%s],\n", esc(c.Closing))
	}
	b.WriteString(")\n\n")

	for _, para := range c.Paragraphs() {
		b.WriteString(esc(para))
		b.WriteString("\n\n")
	}

	return b.String()
}

// ErrNoTypst reports that the typst binary is not on PATH. Callers treat this
// as non-fatal: the .typ source is still written and saved.
var ErrNoTypst = fmt.Errorf("typst binary not found on PATH (install with: brew install typst)")

// Available reports whether typst can be invoked.
func Available() bool {
	_, err := exec.LookPath("typst")
	return err == nil
}

// Write writes the generated .typ (and the resume template beside it) into dir
// and returns the path to the .typ file.
func Write(dir, base, src string) (string, error) {
	return WriteWith(dir, base, src, TemplateName, templateTypst)
}

// WriteWith is Write with an explicit companion template, so cover letters can
// ship their own alongside the generated source. Both files land in dir, which
// is what lets the generated .typ compile standalone.
func WriteWith(dir, base, src, tmplName, tmplSrc string) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	tmplPath := filepath.Join(dir, tmplName)
	if err := os.WriteFile(tmplPath, []byte(tmplSrc), 0o644); err != nil {
		return "", fmt.Errorf("write template: %w", err)
	}
	typPath := filepath.Join(dir, base+".typ")
	if err := os.WriteFile(typPath, []byte(src), 0o644); err != nil {
		return "", fmt.Errorf("write typst source: %w", err)
	}
	return typPath, nil
}

// PDF compiles typPath to a PDF next to it and returns the PDF path.
func PDF(typPath string) (string, error) {
	if !Available() {
		return "", ErrNoTypst
	}
	pdfPath := strings.TrimSuffix(typPath, ".typ") + ".pdf"
	cmd := exec.Command("typst", "compile", "--root", filepath.Dir(typPath), typPath, pdfPath)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("typst compile failed: %w\n%s", err, stderr.String())
	}
	return pdfPath, nil
}
